/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ESTUDIANTE
 */
public class hc extends javax.swing.JFrame {

    /**
     * Creates new form hc
     */
    public hc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jTextField17 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jComboBox6 = new javax.swing.JComboBox<String>();
        jComboBox7 = new javax.swing.JComboBox<String>();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<String>();
        jLabel30 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<String>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<String>();
        jLabel33 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<String>();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<String>();
        jComboBox13 = new javax.swing.JComboBox<String>();
        jComboBox14 = new javax.swing.JComboBox<String>();
        jComboBox15 = new javax.swing.JComboBox<String>();
        jComboBox16 = new javax.swing.JComboBox<String>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<String>();
        jComboBox18 = new javax.swing.JComboBox<String>();
        jComboBox19 = new javax.swing.JComboBox<String>();
        jComboBox20 = new javax.swing.JComboBox<String>();
        jComboBox21 = new javax.swing.JComboBox<String>();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox<String>();
        jComboBox23 = new javax.swing.JComboBox<String>();
        jComboBox24 = new javax.swing.JComboBox<String>();
        jComboBox25 = new javax.swing.JComboBox<String>();
        jComboBox26 = new javax.swing.JComboBox<String>();
        jComboBox27 = new javax.swing.JComboBox<String>();
        jComboBox28 = new javax.swing.JComboBox<String>();
        jComboBox29 = new javax.swing.JComboBox<String>();
        jComboBox30 = new javax.swing.JComboBox<String>();
        jComboBox31 = new javax.swing.JComboBox<String>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TipoDocumento", "Documento", "nombre", "Direccion", "Celular", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(51, 137, 216));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("HISTORIA CLINICA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fecha Visita Medica:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 76, 120, -1));

        jTextField1.setText("00/00/0000");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre del paciente: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Edad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 52, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 257, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha Nacimiento:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, -1));

        jTextField4.setText("00/00/0000");
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Dirrecion:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 257, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Celular:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Reprecentante Legal:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 133, -1, -1));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Celular:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 257, -1));

        jLabel11.setText("IPS PRIMARIA:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 238, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELEECIONE", "N EPS", "SANITAS", "NORVITAL", "UVA VIHONCO", "MEDICUC", "SANARTE", "ESPECIALIZADA", "MILITAR", "PRIVADA", "OTRO" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 235, -1, -1));

        jLabel12.setText("EPS:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 312, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "N EPS", "MEDIMAS", "COOMEVA", "PRIVADO", "COOSALUD", "OTRO" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 309, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Email:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 159, -1, -1));
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 318, -1));

        jLabel14.setText("Solicitado por:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 198, -1, -1));

        jLabel15.setText("Ordenado por:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 277, -1, -1));

        jLabel16.setText("NIT:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 238, -1, -1));
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 235, 101, -1));

        jLabel17.setText("Direccion:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 238, -1, -1));
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 235, 99, -1));

        jLabel18.setText("Telefono:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 238, -1, -1));
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 235, 94, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 261, 940, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 182, 940, 10));

        jLabel19.setText("NIT:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 312, -1, -1));
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 309, 103, -1));

        jLabel20.setText("Dirrecion:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 312, -1, -1));
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 309, 100, -1));

        jLabel21.setText("Telefono:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 312, -1, -1));
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 309, 93, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 347, 940, 10));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Tipo de Afiliado:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "SUBSIDIADO", "COTIZANTE", "INDEPENDIENTE" }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        jLabel23.setText("Estado Actual del paciente:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 388, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 368, 679, 65));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("DX | DIAGNOSTICO DEL PACIENTE");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 451, -1, -1));

        jLabel25.setText("DX PRINCIPAL:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 494, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I10X", "JZ10", "J202", "Z302", "R212" }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 491, -1, -1));
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 491, 307, -1));

        jLabel26.setText("DX 2:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 522, -1, -1));

        jLabel27.setText("DX 3:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 548, -1, -1));

        jLabel28.setText("DX 4:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 574, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I10X", "JZ10", "J202", "Z302", "" }));
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 522, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I10X", "JZ10", "J202", "Z302", "" }));
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 548, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I10X", "JZ10", "J202", "Z302", "" }));
        jPanel2.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 574, -1, -1));
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 522, 307, -1));
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 548, 307, -1));
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 574, 307, -1));

        jLabel29.setText("Tipo de Paciente:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 494, 95, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "Paciente Cronico", "Paciente Cronico Domiciliario", "Paciente con Alta Temprana", "Pte con Traqueostomia", "Pte Neurologico", "Pte con Visita Medica" }));
        jPanel2.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 491, -1, -1));

        jLabel30.setText("Codigo de Paquete:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 525, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "C110", "C112", "C111", "C100", "C113", "C114" }));
        jPanel2.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 522, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 612, 950, 10));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText(" CUIDADOR | AUXILIAR DE ENFERMERIA");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 628, -1, -1));

        jLabel32.setText("Requiere Cuidador: ");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 680, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "SI", "NO" }));
        jPanel2.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 677, -1, -1));

        jLabel33.setText("CANTIDAD EN HORAS:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 715, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "6H", "8H", "12H", "24H" }));
        jPanel2.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 712, -1, -1));

        jLabel34.setText("Estado:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 692, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 677, 625, 55));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 750, 950, 10));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("MEDICAMENTOS");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 771, -1, -1));

        jLabel36.setText("M1:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 807, -1, -1));

        jLabel37.setText("M2:");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 845, -1, -1));

        jLabel38.setText("M3:");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 876, -1, -1));

        jLabel39.setText("M4:");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 907, -1, -1));

        jLabel40.setText("M5:");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 938, -1, -1));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Via", "Oral", "IV", "IM", "SUB", "TOPICA", "SONDA" }));
        jPanel2.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 804, -1, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Via", "Oral", "IV", "IM", "SUB", "TOPICA", "SONDA" }));
        jPanel2.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 842, -1, -1));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Via", "Oral", "IV", "IM", "SUB", "TOPICA", "SONDA" }));
        jPanel2.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 873, -1, -1));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Via", "Oral", "IV", "IM", "SUB", "TOPICA", "SONDA" }));
        jPanel2.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 904, -1, -1));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Via", "Oral", "IV", "IM", "SUB", "TOPICA", "SONDA" }));
        jPanel2.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 935, -1, -1));

        jLabel41.setText("Via Administracion:");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 807, -1, -1));

        jLabel42.setText("Via Administracion:");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 845, -1, -1));

        jLabel43.setText("Via Administracion:");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 876, -1, -1));

        jLabel44.setText("Via Administracion:");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 907, -1, -1));

        jLabel45.setText("Via Administracion:");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 938, -1, -1));

        jLabel46.setText("Por:");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 807, -1, -1));

        jLabel47.setText("Por:");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 845, -1, -1));

        jLabel48.setText("Por:");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 876, -1, -1));

        jLabel49.setText("Por:");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 907, -1, -1));

        jLabel50.setText("Por:");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 938, -1, -1));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0dias", "1dias", "2dias", "3dias", "4dias", "5dias", "6dias", "7dias", "1semana", "2semanas", "3semanas", "4semanas" }));
        jPanel2.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 804, -1, -1));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0dias", "1dias", "2dias", "3dias", "4dias", "5dias", "6dias", "7dias", "1semana", "2semanas", "3semanas", "4semanas" }));
        jPanel2.add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 842, -1, -1));

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0dias", "1dias", "2dias", "3dias", "4dias", "5dias", "6dias", "7dias", "1semana", "2semanas", "3semanas", "4semanas" }));
        jPanel2.add(jComboBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 873, -1, -1));

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0dias", "1dias", "2dias", "3dias", "4dias", "5dias", "6dias", "7dias", "1semana", "2semanas", "3semanas", "4semanas" }));
        jPanel2.add(jComboBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 904, -1, -1));

        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0dias", "1dias", "2dias", "3dias", "4dias", "5dias", "6dias", "7dias", "1semana", "2semanas", "3semanas", "4semanas" }));
        jPanel2.add(jComboBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 935, -1, -1));

        jLabel51.setText("Cada:");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 807, -1, -1));

        jLabel52.setText("Cada:");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 845, -1, -1));

        jLabel53.setText("Cada:");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 876, -1, -1));

        jLabel54.setText("Cada:");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 907, -1, -1));

        jLabel55.setText("Cada:");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 938, -1, -1));

        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0h", "2h", "4h", "6h", "8h", "12h", "24h" }));
        jPanel2.add(jComboBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 804, -1, -1));

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0h", "2h", "4h", "6h", "8h", "12h", "24h" }));
        jPanel2.add(jComboBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 842, -1, -1));

        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0h", "2h", "4h", "6h", "8h", "12h", "24h" }));
        jPanel2.add(jComboBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 873, -1, -1));

        jComboBox25.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0h", "2h", "4h", "6h", "8h", "12h", "24h" }));
        jPanel2.add(jComboBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 904, -1, -1));

        jComboBox26.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0h", "2h", "4h", "6h", "8h", "12h", "24h" }));
        jPanel2.add(jComboBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 935, -1, -1));

        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Acetaminofen", "Clotrimazol", "Midazolan", "Lozartan", "Diclofecano", "Dolex", "Buscapina", "Buscapina Compuesta", "Ensure", "Vitamina C" }));
        jPanel2.add(jComboBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 804, 473, -1));

        jComboBox28.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Acetaminofen", "Clotrimazol", "Midazolan", "Lozartan", "Diclofecano", "Dolex", "Buscapina", "Buscapina Compuesta", "Ensure", "Vitamina C" }));
        jPanel2.add(jComboBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 842, 473, -1));

        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Acetaminofen", "Clotrimazol", "Midazolan", "Lozartan", "Diclofecano", "Dolex", "Buscapina", "Buscapina Compuesta", "Ensure", "Vitamina C" }));
        jPanel2.add(jComboBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 873, 473, -1));

        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Acetaminofen", "Clotrimazol", "Midazolan", "Lozartan", "Diclofecano", "Dolex", "Buscapina", "Buscapina Compuesta", "Ensure", "Vitamina C" }));
        jPanel2.add(jComboBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 904, 473, -1));

        jComboBox31.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Acetaminofen", "Clotrimazol", "Midazolan", "Lozartan", "Diclofecano", "Dolex", "Buscapina", "Buscapina Compuesta", "Ensure", "Vitamina C" }));
        jPanel2.add(jComboBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 935, 473, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 970, 970, 10));

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel57.setText("Fecha de Impresion:");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1100, -1, -1));

        jLabel58.setBackground(new java.awt.Color(204, 204, 204));
        jLabel58.setText("00/00/0000");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 1090, 60, 30));

        jLabel59.setText("La historia clínica es un documento consagrado en el Artículo 34 de la Ley 23 de 1981, “Es un documento privado sometido a reserva, ");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1090, 660, -1));

        jLabel60.setText("que únicamente puede ser conocido por terceros previa autorización del paciente, o en los casos previstos por la Ley.");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1114, -1, 10));

        jLabel6.setText("Documento del paciente:");

        jButton1.setText("Buscar ->");

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medical.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(535, 535, 535)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1))
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox24;
    private javax.swing.JComboBox<String> jComboBox25;
    private javax.swing.JComboBox<String> jComboBox26;
    private javax.swing.JComboBox<String> jComboBox27;
    private javax.swing.JComboBox<String> jComboBox28;
    private javax.swing.JComboBox<String> jComboBox29;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox30;
    private javax.swing.JComboBox<String> jComboBox31;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
